# Generated by Django 4.2.3 on 2023-11-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArhiveVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video_archive/%d_%m_%Y')),
                ('path', models.CharField(max_length=255)),
                ('data_created', models.DateTimeField()),
                ('human_det', models.BooleanField(blank=True)),
                ('cat_det', models.BooleanField(blank=True)),
                ('chiken_det', models.BooleanField(blank=True)),
                ('car_det', models.BooleanField(blank=True)),
            ],
        ),
    ]
