# Generated by Django 4.2.3 on 2023-11-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_video_arhivevideo_video_path_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArhiveVideo',
            new_name='ArchiveVideo',
        ),
    ]
