# Generated by Django 4.2.3 on 2023-11-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_arhivevideo_archivevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivevideo',
            name='video_path',
        ),
    ]
