# Generated by Django 4.2.3 on 2023-12-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_archivevideo_video_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivevideo',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
