# Generated by Django 4.2.3 on 2024-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_data_created_archivevideo_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_expire', models.DateTimeField()),
            ],
        ),
    ]
