# Generated by Django 4.2.3 on 2024-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_name_camera_camera_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='id',
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
