# Generated by Django 4.2.3 on 2024-06-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_camera_id_alter_camera_camera_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivevideo',
            name='camera_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.camera'),
        ),
    ]
