# Generated by Django 4.2.3 on 2024-06-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_archivevideo_camera_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivevideo',
            old_name='camera_name',
            new_name='camera',
        ),
    ]
