FROM python:3.11.4-slim-buster
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
RUN pip install numpy
RUN pip install "psycopg[binary]"  
WORKDIR /code
COPY camera_conn.py /code/
