FROM python:3.11.4-slim-buster
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
RUN pip install numpy
RUN pip install "psycopg[binary]"  
RUN pip install pytz==2023.3.post1
WORKDIR /code
COPY . /code/
